export const EGYPTIAN_CITIES = [
  { en: "Cairo", ar: "القاهرة" },
  { en: "Giza", ar: "الجيزة" },
  { en: "Alexandria", ar: "الإسكندرية" },
  { en: "Shubra El Kheima", ar: "شبرا الخيمة" },
  { en: "Port Said", ar: "بورسعيد" },
  { en: "Suez", ar: "السويس" },
  { en: "Luxor", ar: "الأقصر" },
  { en: "Aswan", ar: "أسوان" },
  { en: "Asyut", ar: "أسيوط" },
  { en: "Ismailia", ar: "الإسماعيلية" },
  { en: "Faiyum", ar: "الفيوم" },
  { en: "Zagazig", ar: "الزقازيق" },
  { en: "Damietta", ar: "دمياط" },
  { en: "Mansoura", ar: "المنصورة" },
  { en: "Tanta", ar: "طنطا" },
  { en: "Beni Suef", ar: "بني سويف" },
  { en: "Sohag", ar: "سوهاج" },
  { en: "Hurghada", ar: "الغردقة" },
  { en: "6th of October City", ar: "مدينة السادس من أكتوبر" },
  { en: "Shibin El Kom", ar: "شبين الكوم" },
  { en: "Banha", ar: "بنها" },
  { en: "Kafr El Sheikh", ar: "كفر الشيخ" },
  { en: "Arish", ar: "العريش" },
  { en: "Mallawi", ar: "ملوي" },
  { en: "10th of Ramadan City", ar: "مدينة العاشر من رمضان" },
  { en: "Bilbeis", ar: "بلبيس" },
  { en: "Marsa Matruh", ar: "مرسى مطروح" },
  { en: "Idfu", ar: "إدفو" },
  { en: "Mit Ghamr", ar: "ميت غمر" },
  { en: "Al Mahalla Al Kubra", ar: "المحلة الكبرى" },
  { en: "Qena", ar: "قنا" },
  { en: "Minya", ar: "المنيا" },
  { en: "Damanhur", ar: "دمنهور" },
  { en: "New Cairo", ar: "القاهرة الجديدة" },
  { en: "Helwan", ar: "حلوان" },
  { en: "Obour City", ar: "مدينة العبور" },
  { en: "Nasr City", ar: "مدينة نصر" },
  { en: "Maadi", ar: "المعادي" },
  { en: "Sheikh Zayed City", ar: "مدينة الشيخ زايد" },
  { en: "New Administrative Capital", ar: "العاصمة الإدارية الجديدة" },
  { en: "Sharm El Sheikh", ar: "شرم الشيخ" },
  { en: "El Gouna", ar: "الجونة" },
  { en: "Dahab", ar: "دهب" },
  { en: "Nuweiba", ar: "نويبع" },
  { en: "Ain Sokhna", ar: "العين السخنة" },
  { en: "Borg El Arab", ar: "برج العرب" },
  { en: "Sadat City", ar: "مدينة السادات" },
  { en: "Badr City", ar: "مدينة بدر" },
  { en: "Quesna", ar: "قويسنا" },
  { en: "El Kharga", ar: "الخارجة" },
] as const

export function getArabicCityName(englishName: string): string {
  if (!englishName) return ""
  const city = EGYPTIAN_CITIES.find(c => c.en === englishName)
  return city ? city.ar : englishName
}
